# Generated by Django 4.0.1 on 2022-01-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='file_name',
        ),
    ]
