# Generated by Django 4.0.1 on 2022-01-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0002_remove_excelfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
